"""
Reporting module — generates professional pentest reports from session data.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, TYPE_CHECKING

from jinja2 import Environment, BaseLoader

from relic.modules.base import BaseModule, ModuleResult

if TYPE_CHECKING:
    from relic.core.engine import Engine

log = logging.getLogger("relic.modules.reporting")


REPORT_TEMPLATE = """\
# Penetration Testing Report

> **Generated by Relic** — {{ timestamp }}

---

## 1. Executive Summary

This report documents the findings from a penetration testing engagement
conducted against **{{ target }}**.

- **Scope:** {{ scope }}
- **Date:** {{ date }}
- **Session ID:** {{ session_id }}
- **Total Commands Executed:** {{ command_count }}
- **Findings:** {{ finding_count }} ({{ critical }} critical, {{ high }} high, {{ medium }} medium, {{ low }} low)

---

## 2. Scope & Methodology

**Target:** {{ target }}
**Scope:** {{ scope }}

The assessment followed a structured methodology:
1. **Reconnaissance** — Passive and active information gathering
2. **Enumeration** — Service and vulnerability enumeration
3. **Exploitation** — Attempting to exploit discovered vulnerabilities
4. **Post-Exploitation** — Privilege escalation and lateral movement
5. **Reporting** — Documenting all findings and recommendations

---

## 3. Findings

{% if findings %}
| # | Title | Severity | Type |
|---|-------|----------|------|
{% for f in findings -%}
| {{ loop.index }} | {{ f.title | default('Untitled') }} | {{ f.severity | default('info') | upper }} | {{ f.type | default('general') }} |
{% endfor %}

{% for f in findings %}
### 3.{{ loop.index }} — {{ f.title | default('Finding') }}

- **Severity:** {{ f.severity | default('info') | upper }}
- **Type:** {{ f.type | default('general') }}
{% if f.description %}- **Description:** {{ f.description }}{% endif %}
{% if f.detail %}- **Detail:** {{ f.detail }}{% endif %}
{% if f.url %}- **URL:** {{ f.url }}{% endif %}
{% if f.port %}- **Port:** {{ f.port }}{% endif %}

{% endfor %}
{% else %}
*No findings recorded in this session.*
{% endif %}

---

## 4. Recommendations

{% if findings -%}
{% for f in findings -%}
- **{{ f.title | default('Finding') }}**: Remediate the {{ f.severity | default('info') }}-severity {{ f.type | default('') }} issue.
{% endfor %}
{% else -%}
No specific recommendations — no vulnerabilities were identified.
{% endif %}

---

## 5. Command Log (Summary)

<details>
<summary>Click to expand ({{ command_count }} commands)</summary>

{% for entry in history[:100] -%}
```
[{{ entry.source }}] $ {{ entry.command }}
{{ entry.output[:500] }}
```
{% endfor %}

{% if command_count > 100 -%}
*... and {{ command_count - 100 }} more commands. See full session log.*
{% endif %}

</details>

---

*Report generated by Relic v{{ version }}*
"""


class ReportModule(BaseModule):
    """Generate a Markdown penetration testing report."""

    name = "report"
    description = "Generate a pentest report from session data"
    category = "reporting"

    def get_commands(self, **kwargs: Any) -> list[dict[str, str]]:
        return []  # This module doesn't execute VM commands

    async def run(self, engine: "Engine", output_dir: str = "./reports", **kwargs: Any) -> ModuleResult:
        from relic import __version__

        session = engine.sessions.active
        if not session:
            return ModuleResult(module=self.name, success=False, output="No active session")

        findings = session.findings
        severity_counts = {"critical": 0, "high": 0, "medium": 0, "low": 0}
        for f in findings:
            sev = f.get("severity", "info").lower()
            if sev in severity_counts:
                severity_counts[sev] += 1

        env = Environment(loader=BaseLoader(), autoescape=False)
        template = env.from_string(REPORT_TEMPLATE)

        now = datetime.now(timezone.utc)
        report = template.render(
            timestamp=now.isoformat(),
            date=now.strftime("%Y-%m-%d"),
            target=session.meta.target,
            scope=session.meta.scope,
            session_id=session.meta.id,
            command_count=len(session.history),
            finding_count=len(findings),
            critical=severity_counts["critical"],
            high=severity_counts["high"],
            medium=severity_counts["medium"],
            low=severity_counts["low"],
            findings=findings,
            history=[e.model_dump() for e in session.history],
            version=__version__,
        )

        # Write report to disk
        out = Path(output_dir).expanduser()
        out.mkdir(parents=True, exist_ok=True)
        filename = f"relic-report-{session.meta.id}-{now.strftime('%Y%m%d-%H%M%S')}.md"
        filepath = out / filename
        filepath.write_text(report, encoding="utf-8")

        log.info("Report written to %s", filepath)
        return ModuleResult(
            module=self.name,
            output=f"Report saved to {filepath}",
            raw_data={"path": str(filepath)},
        )


REPORTING_MODULES: dict[str, type[BaseModule]] = {
    "report": ReportModule,
}
